### ISSUE TITLE
Allow to only include a sub-part of the default commit types

### ISSUE THREAD

**Issue by SirWindfield** [SirWindfield/git-cm#3]
Currently, default types are either all-in or none. It would be nice to have an option that would allow someone to only use certain parts of it:

```toml
[package.metadata.commits]
include = ["feat", "fix", "refactor"] # maybe `use` as a key fits better here...
```
